### ISSUE TITLE
Update contact page

### ISSUE THREAD

**Issue by Per-Starke** [gernotstarke/esabuch.de-site#42]
The contact page has some outdated links like xing, the blog, maybe twitter... And no up to date social links.
Maybe this should be updated?
Same for the gernotstarke.de-site, but not as outdated as this one :D 
@gernotstarke

**Comment by gernotstarke** [comment]
please update:
* add linkedin (gernotstarke)
* remove xing
* remove twitter
* add mastodon (imho the most current links are on quality.arc42.org)
