### ISSUE TITLE
add "Literatur", aktuell Platzhalterseite

### ISSUE THREAD

**Issue by gernotstarke** [gernotstarke/esabuch.de-site#45]
ich werde zukünftig alle Literaturhinweise online pflegen - damit Leute den Links besser folgen können, bzw. ich die Links ab-und-zu überprüfen kann.

Zuerst machen wir dafür eine Platzhalter-Seite, und fügen ein paar Verweise ein:

[Ambler-12] Ambler, S.: [www.agilemodeling.com](file:///C:/Users/rajaram.p/AppData/Local/Temp/www.agilemodeling.com). Ratschläge für schlanke und agile Modellierung.
[arc42] Hruschka, P., Starke, G.: arc42 – Ressourcen für Software-Architekten. https://arc42.de/ beziehungsweise https://arc42.org/. Praktische Beispiele für den Einsatz von arc42 finden Sie unter https://leanpub.com/arc42byexample.
[arc42-QA] (Freie) Sammlung exemplarischer Qualitätsanforderungen verschiedener Kategorien, https://quality.arc42.org/.
[Avram+06] Avram, A., Marinescu, F.: Domain Driven Design Quickly. PDF-Version online, http://infoq.com/books/domain-driven-design-quickly.
[Bass+21] Bass, L., Clements, P., Kazman, R.: Software Architecture in Practice. 4. Auflage. Addison-Wesley, 2021.
[Brandolini17] Brandolini, Alberto: Introducing Event Storming: An act of Deliberate Collective Learning. E-Book: https://leanpub.com/introducing_eventstorming.
[Brewer00] Brewer, E.: CAP-Theorem: http://www.cs.berkeley.edu/~brewer/cs262b-2004/PODC-keynote.pdf.
[Brooks95] Brooks, F.: The Mythical Man-Month, Anniversary Edition. Addison-Wesley, 1995.
[Brown] Simon Brown, https://simonbrown.je/.

**Comment by Per-Starke** [comment]
@gernotstarke Du hast doch schon eine "Links" Seite, was genau soll der Unterschied zur Literatur-Seite sein?

[https://www.esabuch.de/addons/04-literatur-links](https://www.esabuch.de/addons/04-literatur-links)

Need to understand the planned difference between those.
